global:
  mlp:
    encryption:
      key: "encryption-key"

turing:
  uiConfig: null # Not needed as we only test API
  openApiSpecOverrides:
    components:
      schemas:
        ExperimentEngineType:
          enum:
          - nop
          - proprietary

postgresql: &postgresql
  persistence:
    enabled: false

merlin:
  postgresql: *postgresql

mlp:
  postgresql: *postgresql
