apiVersion: v2
name: turingcluster
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
dependencies:
- name: spark-operator
  version: 1.1.7
  repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
