# Do note that the following ports to the Kubernetes master must be open:
# For Knative: 8443
# For Spark operator: 8080
# Other gotchas: Helm delete might take some time due to the deletion of knative namespace.
#                Best to run it with an extended timeout, like helm delete <RELEASE> --timeout 15m

turingcluster:
  image:
    # -- Docker registry for Turing cluster init
    registry: ghcr.io/
    # -- Docker image repository for Turing cluster init
    repository: gojek/turing-cluster-init
    # -- Docker image tag for Turing cluster init
    tag: latest
    pullPolicy: IfNotPresent

  # -- Istio version to use
  istioVersion: 1.9.9
  # -- Knative Version to use
  knativeVersion: 0.18.3
  knativeIstioVersion: 0.18.1

  # -- Base config, more can be seen here: https://github.com/istio/istio/blob/1.9.9/manifests/charts/base/values.yaml
  istioBaseConfig: {}
  # -- Discovery config, more can be seen here: https://github.com/istio/istio/blob/1.9.9/manifests/charts/istio-control/istio-discovery/values.yaml
  istioDiscoveryConfig: {}
  # -- Ingress gateway config, more can be seen here: https://github.com/istio/istio/blob/1.9.9/manifests/charts/gateways/istio-ingress/values.yaml
  istioIngressConfig: {}

# -- Override any spark-operator values here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/charts/spark-operator-chart/README.md
spark-operator:
  # -- number of replicas
  replicas: 1
  webhook:
    # -- this is needed to be set to true, if not the configmaps will not load
    enable: true
  # -- Resources requests and limits for spark operator. This should be set 
  # according to your cluster capacity and service level objectives.
  # Reference: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources: {}
  image:
    # -- repository of the spark operator
    repository: gcr.io/spark-operator/spark-operator
    # -- image tag of the spark operator
    tag: v1beta2-1.2.3-3.1.1
  # -- Hook weights need to be overridden in order to prevent race condition of the deletion of 
  # the service account and cluster init
  cleanupAnnotations:
    "helm.sh/hook": pre-delete, pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
