apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "turing-init.fullname" . }}-cleanup
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "10"
  labels:
    {{- include "turing-init.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ include "turing-init.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: knative-istio-cleanup
        image: {{ .Values.turing-init.image.registry }}{{ .Values.turing-init.image.repository }}:{{ .Values.turing-init.image.tag }}
        command:
        - /bin/bash
        - -c
        args:
        - /app/cleanup.sh
        env:
        - name: KNATIVE_VERSION
          value: {{ .Values.turing-init.knativeVersion }}
        - name: KNATIVE_ISTIO_VERSION
          value: {{ .Values.turing-init.knativeIstioVersion }}
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: RELEASE_NAMESPACE
          value: {{ .Release.Namespace }}
        imagePullPolicy: {{ .Values.turing-init.image.pullPolicy }}
