version: '3.1'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.52.0
    ports:
      - 5555:8080
    volumes:
      - ./doc:/app:ro
    environment:
      - LAYOUT=BaseLayout
      - SWAGGER_JSON=/app/openapi.yaml
