name: swagger

on:
  push:
    paths:
    - ".github/workflows/swagger.yaml"
    - "api/api/**"
  pull_request:
    branches:
    - main

jobs:
  publish-docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api/api
    env:
      DOCKER_REGISTRY: ghcr.io/gojek
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build image
        run: make build-image

      - name: Setup GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish image
        run: docker push ${{ env.DOCKER_REGISTRY }}/turing/batch-ensembler:$(make version)
